name: getxflutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.5
  firebase_core: 2.25.4
  get: 4.6.6
  cloud_firestore: 4.15.5
  firebase_storage: 11.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

